hh_name = "//h1/text()"
sj_name = "//h1/text()"
hh_salary = "//p/span[@data-qa='bloko-header-2']/text()"
# sj_salary = "//span[contains(@class, '_3mfro _2Wp8I PlM3e _2JVkc')]/text()"
sj_salary = "//span[contains(@class,'_1OuF_ ZON4b')]//span/text()"